---

  # This is a basic workflow to get started with FortiDevSec
  
  name: FortiDevSec
  
  # Controls when the workflow will run
  on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  
    # Allows this workflow to be run manually from the Actions tab
    workflow_dispatch:
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    # TThis job is called called "fortidevsec"
    fortidevsec:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
  
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
        - uses: actions/checkout@v2
  
        # Runs a set of commands using the runners shell
        - name: SAST
          run: |
            env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
            docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
            docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
        #- name: DAST
        #  run: |
        #      env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
        #      docker pull registry.fortidevsec.forticloud.com/fdevsec_dast:latest
        #      docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_dast:latest
